### ISSUE TITLE
Cannot get the tm_desc file after using "thot_tm_train"

### ISSUE THREAD

**Issue by chaosneverland** [daormar/thot#1]
MY command is :  thot_tm_train -s /usr/local/share/thot/toy_corpus/train.sp -t /usr/local/share/thot/toy_corpus/train.en -o /home/gtct/yuchao/mt/tm_outdir/
And  I just get a "main" directory with nothing.I can find tm_desc nowhere.

**Comment by amonmoce** [comment]
I tried it under the root folder (where there are configure , INSTALL, etc) and also under the example/toy_corpus folder ... but I got the following error. 
/usr/local/bin/thot_gen_sw_model: error while loading shared libraries: libthot.so.0: cannot open shared object file: No such file or directory

**Comment by daormar** [comment]
Dear amonmoce, first of all, sorry for my delayed response. Some days ago I committed a patch that tries to solve the issue. I cannot confirm that the patch really works, since I haven't been able to reproduce the error in a whole set of different platforms. 

I think the error you get is due to portability problems when executing the "reconf" script, so I have uploaded a new version of it. Please, would you be so kind to execute "git pull", and try if now everything works fine after reinstalling the package?

**Comment by tianliang0123** [comment]
try to install 
sudo apt-get install libgconf2-dev
and then install the toolkit again. I use this to solve this problem.

**Comment by amonmoce** [comment]
With the updates in the repo, the command works fine. Thanks guys.

**Comment by pixelhunter** [comment]
I still get the same error above when on a AWS Ubuntu instance. It works fine local on Mac OSX though.
All above suggestions didn't help. Please help.

**Comment by daormar** [comment]
First of all, Thot is completely independent of Moses, so you don't need to install Moses to make Thot work. What you need instead is to install `autoconf`, `autoconf-archive`, `automake` and `libtool` packages using `apt-get` if you are using Ubuntu, as explained in the Thot manual.

On the other hand, have you ensured that you are working with the last version of Thot? If not, please execute `git pull` and then reinstall the package from the beginning.
